import type { ProCastSession } from "@/types/worldcup-exclusives"

export const PRO_CAST_SESSIONS: ProCastSession[] = [
  {
    id: "procast-beckham-corner",
    slug: "beckham-usa-corner",
    title: "What would Beckham do on this corner?",
    subtitle: "Near-post flick, second-ball hunting, and the run I would've made at USA '94",
    matchLabel: "USA 2–1 COL · Live · 67'",
    minute: 67,
    type: "corner",
    homeTeamCode: "USA",
    awayTeamCode: "COL",
    durationSeconds: 14,
    castTagline: "Alternate feed · ex-player commentary + telestrator",
    host: {
      name: "David Beckham",
      title: "England legend · Set-piece specialist · MLS ambassador",
      initials: "DB",
      accentColor: "#c8102e",
      firstWorldCup: "1998 — my first World Cup, age 23, terrified and trying to look calm",
      bio: "Took corners for England for a decade. If I'm in the corner arc right now, I'm already counting bodies in the box.",
    },
    frames: [
      {
        time: 0,
        ball: { x: 98, y: 15 },
        phase: "Corner — Beckham breaks it down",
        players: [
          { id: "gk-a", team: "away", label: "GK", x: 95, y: 50 },
          { id: "cb1", team: "away", x: 88, y: 42 },
          { id: "cb2", team: "away", x: 88, y: 58 },
          { id: "us9", team: "home", label: "9", x: 82, y: 48 },
          { id: "us10", team: "home", label: "10", x: 78, y: 35 },
          { id: "us19", team: "home", label: "19", x: 75, y: 62 },
        ],
      },
      {
        time: 3,
        ball: { x: 90, y: 44 },
        phase: "In-swinging — near post",
        players: [
          { id: "gk-a", team: "away", label: "GK", x: 94, y: 46 },
          { id: "us9", team: "home", label: "9", x: 86, y: 44 },
          { id: "us10", team: "home", label: "10", x: 84, y: 38 },
          { id: "us19", team: "home", label: "19", x: 80, y: 55 },
        ],
      },
      {
        time: 6,
        ball: { x: 92, y: 52 },
        phase: "Second ball — this is the plan",
        players: [
          { id: "gk-a", team: "away", label: "GK", x: 93, y: 50 },
          { id: "us19", team: "home", label: "19", x: 88, y: 52 },
          { id: "cb2", team: "away", x: 86, y: 56 },
        ],
      },
      {
        time: 9,
        ball: { x: 96, y: 51 },
        phase: "GOAL — Balogun",
        players: [
          { id: "gk-a", team: "away", label: "GK", x: 96, y: 54 },
          { id: "us19", team: "home", label: "19", x: 94, y: 50 },
        ],
      },
    ],
    annotations: [
      {
        id: "decoy-run",
        startTime: 0,
        endTime: 4,
        type: "run_path",
        points: [
          { x: 78, y: 35 },
          { x: 84, y: 40 },
          { x: 86, y: 44 },
        ],
        label: "Decoy run",
        color: "#60a5fa",
      },
      {
        id: "near-post",
        startTime: 0,
        endTime: 6,
        type: "circle",
        center: { x: 90, y: 44 },
        radius: 4,
        label: "Near post target",
        color: "#fbbf24",
      },
      {
        id: "second-ball-zone",
        startTime: 4,
        endTime: 10,
        type: "zone",
        from: { x: 84, y: 48 },
        to: { x: 94, y: 58 },
        label: "Second-ball zone",
        color: "#34d399",
      },
      {
        id: "beckham-option",
        startTime: 2,
        endTime: 7,
        type: "arrow",
        from: { x: 75, y: 62 },
        to: { x: 88, y: 52 },
        label: "What I'd do: arrive late",
        color: "#f472b6",
      },
    ],
    commentary: [
      {
        time: 0,
        speaker: "David Beckham",
        speakerTitle: "What Would The Pros Do",
        type: "first_wc",
        text: "First World Cup, you're thinking about everything except the football — the crowd, the anthem, whether your kit fits right. By your third, you're reading the keeper's body language before the ball leaves your foot.",
        telestratorIds: [],
      },
      {
        time: 2,
        speaker: "David Beckham",
        speakerTitle: "What Would The Pros Do",
        type: "what_if",
        text: "If this were my corner, I'm going inswinger to the near post — see the yellow circle? Number 9 isn't trying to score. He's blocking the keeper. That's textbook.",
        telestratorIds: ["near-post", "decoy-run"],
      },
      {
        time: 5,
        speaker: "David Beckham",
        speakerTitle: "What Would The Pros Do",
        type: "strategy",
        text: "The header goes loose — and THIS is what we rehearse. I'd be the pink arrow, arriving late into the green zone. Not the first jump. The second one wins World Cups.",
        telestratorIds: ["second-ball-zone", "beckham-option"],
      },
      {
        time: 9,
        speaker: "David Beckham",
        speakerTitle: "What Would The Pros Do",
        type: "reaction",
        text: "Balogun does exactly that. That's not luck — someone on the US staff watched a lot of England corners in '98.",
        telestratorIds: ["second-ball-zone"],
      },
    ],
    takeaway:
      "Pros don't aim for the first header on a corner. They design chaos — decoy runs, near-post flicks, and a late runner into the second-ball zone.",
  },
  {
    id: "procast-zidane-freekick",
    slug: "zidane-free-kick-wall",
    title: "Zidane reads the wall — and the gap",
    subtitle: "Free kick geometry, jump timing, and what I saw before France '98",
    matchLabel: "ARG 3–0 SEN · Live · 8'",
    minute: 8,
    type: "free_kick",
    homeTeamCode: "ARG",
    awayTeamCode: "SEN",
    durationSeconds: 12,
    castTagline: "Alternate feed · Zidane on set pieces",
    host: {
      name: "Zinédine Zidane",
      title: "France 98 champion · Midfield maestro",
      initials: "ZZ",
      accentColor: "#0055a4",
      firstWorldCup: "1998 — home tournament, hair shaved, pressure like nothing before",
      bio: "Scored two headers in a World Cup final. Free kicks are chess — you move the wall before you move the ball.",
    },
    frames: [
      {
        time: 0,
        ball: { x: 72, y: 38 },
        phase: "22 yards — wall setup",
        players: [
          { id: "wall1", team: "away", x: 78, y: 42 },
          { id: "wall2", team: "away", x: 78, y: 48 },
          { id: "wall3", team: "away", x: 78, y: 54 },
          { id: "gk-s", team: "away", label: "GK", x: 92, y: 50 },
          { id: "messi", team: "home", label: "10", x: 70, y: 40 },
        ],
      },
      {
        time: 4,
        ball: { x: 74, y: 38 },
        phase: "Wall jumps early",
        players: [
          { id: "wall1", team: "away", x: 78, y: 38 },
          { id: "wall2", team: "away", x: 78, y: 44 },
          { id: "messi", team: "home", label: "10", x: 71, y: 40 },
        ],
      },
      {
        time: 7,
        ball: { x: 85, y: 46 },
        phase: "Under the wall",
        players: [
          { id: "wall2", team: "away", x: 78, y: 42 },
          { id: "gk-s", team: "away", label: "GK", x: 90, y: 48 },
          { id: "messi", team: "home", label: "10", x: 72, y: 40 },
        ],
      },
      {
        time: 10,
        ball: { x: 96, y: 50 },
        phase: "GOAL",
        players: [
          { id: "gk-s", team: "away", label: "GK", x: 95, y: 52 },
          { id: "messi", team: "home", label: "10", x: 74, y: 40 },
        ],
      },
    ],
    annotations: [
      {
        id: "wall-gap",
        startTime: 0,
        endTime: 8,
        type: "zone",
        from: { x: 76, y: 36 },
        to: { x: 82, y: 44 },
        label: "Gap under wall",
        color: "#f87171",
      },
      {
        id: "wall-line",
        startTime: 0,
        endTime: 5,
        type: "line",
        from: { x: 78, y: 38 },
        to: { x: 78, y: 58 },
        label: "Wall line",
        color: "#fbbf24",
      },
      {
        id: "shot-path",
        startTime: 4,
        endTime: 10,
        type: "arrow",
        from: { x: 72, y: 38 },
        to: { x: 96, y: 50 },
        label: "Low driven",
        color: "#a78bfa",
      },
      {
        id: "keeper-view",
        startTime: 6,
        endTime: 10,
        type: "circle",
        center: { x: 90, y: 48 },
        radius: 3,
        label: "Keeper late",
        color: "#60a5fa",
      },
    ],
    commentary: [
      {
        time: 0,
        speaker: "Zinédine Zidane",
        speakerTitle: "What Would The Pros Do",
        type: "first_wc",
        text: "Before France 98, I couldn't sleep. You hear the word 'World Cup' and think of legends — then you walk onto the pitch and it's just grass and a ball. The grass is the same everywhere.",
        telestratorIds: ["wall-line"],
      },
      {
        time: 2,
        speaker: "Zinédine Zidane",
        speakerTitle: "What Would The Pros Do",
        type: "what_if",
        text: "Messi sees the red zone — the gap at the near side of the wall. If I am taking this, I am not going over. I wait for them to jump.",
        telestratorIds: ["wall-gap", "wall-line"],
      },
      {
        time: 5,
        speaker: "Zinédine Zidane",
        speakerTitle: "What Would The Pros Do",
        type: "strategy",
        text: "They jump on his first step. The purple arrow — low, hard, through the gap. The keeper in the blue circle is screened. Nothing he can do.",
        telestratorIds: ["shot-path", "keeper-view", "wall-gap"],
      },
      {
        time: 9,
        speaker: "Zinédine Zidane",
        speakerTitle: "What Would The Pros Do",
        type: "reaction",
        text: "Simple. Cruel. Perfect. This is why you put your best foot on the ball at 22 yards.",
        telestratorIds: ["shot-path"],
      },
    ],
    takeaway:
      "Free kicks aren't about power — they're about reading the wall's jump and hitting the gap they leave behind.",
  },
  {
    id: "procast-beckham-offside",
    slug: "beckham-offside-explained",
    title: "Beckham draws the offside line — live",
    subtitle: "Telestrator lesson: when the flag goes up, what's actually being measured?",
    matchLabel: "BRA 0–0 MAR · Live · 52' · Counter broken",
    minute: 52,
    type: "offside",
    homeTeamCode: "BRA",
    awayTeamCode: "MAR",
    durationSeconds: 10,
    castTagline: "Rules school · telestrator edition",
    host: {
      name: "David Beckham",
      title: "What Would The Pros Do · Rules corner",
      initials: "DB",
      accentColor: "#c8102e",
      firstWorldCup: "1998 — I learned offside the hard way in a friendly before the tournament",
      bio: "Been on both sides of the flag. Let me show you the line the TV doesn't always draw clearly.",
    },
    frames: [
      {
        time: 0,
        ball: { x: 52, y: 42 },
        phase: "Pass played — check the line",
        players: [
          { id: "br11", team: "home", label: "11", x: 72, y: 28 },
          { id: "br9", team: "home", label: "9", x: 68, y: 48 },
          { id: "def1", team: "away", x: 65, y: 38 },
          { id: "def2", team: "away", x: 65, y: 52 },
          { id: "gk-m", team: "away", label: "GK", x: 92, y: 50 },
        ],
      },
      {
        time: 3,
        ball: { x: 62, y: 35 },
        phase: "Winger receives — flag up?",
        players: [
          { id: "br11", team: "home", label: "11", x: 70, y: 30 },
          { id: "def1", team: "away", x: 65, y: 38 },
          { id: "def2", team: "away", x: 65, y: 52 },
        ],
      },
      {
        time: 6,
        ball: { x: 70, y: 32 },
        phase: "Onside — line held",
        players: [
          { id: "br11", team: "home", label: "11", x: 68, y: 32 },
          { id: "def1", team: "away", x: 65, y: 38 },
        ],
      },
    ],
    annotations: [
      {
        id: "offside-line",
        startTime: 0,
        endTime: 10,
        type: "offside_line",
        from: { x: 65, y: 20 },
        to: { x: 65, y: 60 },
        label: "Second-to-last defender",
        color: "#ef4444",
      },
      {
        id: "attacker-pos",
        startTime: 0,
        endTime: 4,
        type: "circle",
        center: { x: 72, y: 28 },
        radius: 3,
        label: "Winger at pass",
        color: "#60a5fa",
      },
      {
        id: "legal-run",
        startTime: 4,
        endTime: 10,
        type: "run_path",
        points: [
          { x: 72, y: 28 },
          { x: 70, y: 30 },
          { x: 68, y: 32 },
        ],
        label: "Level with last defender",
        color: "#34d399",
      },
    ],
    commentary: [
      {
        time: 0,
        speaker: "David Beckham",
        speakerTitle: "What Would The Pros Do · Rules",
        type: "rule",
        text: "New fans — offside isn't where the player stands now. It's where they are when the PASS is played. Watch the red line — that's the second-to-last defender.",
        telestratorIds: ["offside-line"],
      },
      {
        time: 2,
        speaker: "David Beckham",
        speakerTitle: "What Would The Pros Do · Rules",
        type: "rule",
        text: "The blue circle is the winger at the moment of the pass. Is he past the red line? No — he's level. That's onside. The flag should stay down.",
        telestratorIds: ["offside-line", "attacker-pos"],
      },
      {
        time: 5,
        speaker: "David Beckham",
        speakerTitle: "What Would The Pros Do · Rules",
        type: "what_if",
        text: "If I were the winger, I'm timing the green run — start when the pass is already on its way, stay level with that last defender. Sprint too early, you're offside. Sprint late, you're useless.",
        telestratorIds: ["legal-run", "offside-line"],
      },
    ],
    takeaway:
      "Offside is judged at the moment of the pass, not the moment of the shot. The second-to-last defender sets the line.",
  },
  {
    id: "procast-zidane-backpass",
    slug: "zidane-keeper-backpass-rule",
    title: "Why the keeper can't pick that up",
    subtitle: "The back-pass rule — Zidane explains the '90 law that changed goalkeeping forever",
    matchLabel: "MEX 1–1 CAN · Live · 41' · Goal kick situation",
    minute: 41,
    type: "build_up",
    homeTeamCode: "MEX",
    awayTeamCode: "CAN",
    durationSeconds: 9,
    castTagline: "Rules school · keeper restrictions",
    host: {
      name: "Zinédine Zidane",
      title: "What Would The Pros Do · Rules corner",
      initials: "ZZ",
      accentColor: "#0055a4",
      bio: "In 1998 we could still roll it back to the keeper and he could pick it up. Not anymore — let me show you why.",
    },
    frames: [
      {
        time: 0,
        ball: { x: 25, y: 50 },
        phase: "Defender under pressure",
        players: [
          { id: "def-m", team: "home", x: 22, y: 48 },
          { id: "gk-m", team: "home", label: "GK", x: 8, y: 50 },
          { id: "press", team: "away", x: 28, y: 48 },
        ],
      },
      {
        time: 3,
        ball: { x: 12, y: 50 },
        phase: "Header back to keeper",
        players: [
          { id: "def-m", team: "home", x: 18, y: 48 },
          { id: "gk-m", team: "home", label: "GK", x: 8, y: 50 },
        ],
      },
      {
        time: 6,
        ball: { x: 10, y: 50 },
        phase: "Indirect free kick!",
        players: [
          { id: "gk-m", team: "home", label: "GK", x: 8, y: 50 },
          { id: "ref", team: "away", x: 12, y: 45 },
        ],
      },
    ],
    annotations: [
      {
        id: "back-pass",
        startTime: 2,
        endTime: 8,
        type: "arrow",
        from: { x: 22, y: 48 },
        to: { x: 8, y: 50 },
        label: "Deliberate back-pass (not foot)",
        color: "#f87171",
      },
      {
        id: "no-hands",
        startTime: 5,
        endTime: 9,
        type: "zone",
        from: { x: 4, y: 44 },
        to: { x: 14, y: 56 },
        label: "Keeper can't use hands here",
        color: "#fbbf24",
      },
    ],
    commentary: [
      {
        time: 0,
        speaker: "Zinédine Zidane",
        speakerTitle: "What Would The Pros Do · Rules",
        type: "rule",
        text: "Quick rule for new fans: if a teammate passes to the keeper deliberately — with anything other than the foot — the keeper CANNOT pick it up with their hands.",
        telestratorIds: [],
      },
      {
        time: 3,
        speaker: "Zinédine Zidane",
        speakerTitle: "What Would The Pros Do · Rules",
        type: "rule",
        text: "See the red arrow? Header back to the keeper. That's deliberate. He catches it — that's an indirect free kick inside the box. Harsh, but the law.",
        telestratorIds: ["back-pass", "no-hands"],
      },
      {
        time: 6,
        speaker: "Zinédine Zidane",
        speakerTitle: "What Would The Pros Do · Rules",
        type: "what_if",
        text: "What would I do as the defender? Never. Clear it. Boot it into row Z. My first World Cup, I saw a team concede from this. You don't forget.",
        telestratorIds: ["back-pass"],
      },
    ],
    takeaway:
      "Goalkeepers can only use their hands on a back-pass if it came off a teammate's foot. Headers, chests, knees — the ref awards an indirect free kick.",
  },
]

export function getProCastBySlug(slug: string): ProCastSession | undefined {
  return PRO_CAST_SESSIONS.find((s) => s.slug === slug)
}

export function getLiveProCastForMatch(homeCode: string, awayCode: string): ProCastSession | undefined {
  return PRO_CAST_SESSIONS.find(
    (s) =>
      (s.homeTeamCode === homeCode && s.awayTeamCode === awayCode) ||
      (s.homeTeamCode === awayCode && s.awayTeamCode === homeCode)
  )
}
