import type { GroupStanding, Match, TournamentSnapshot } from "@/types/worldcup"
import { SAMPLE_TEAMS, getTeamByCode } from "./teams"
import { STORIES } from "./content"

function team(code: string) {
  const t = getTeamByCode(code)
  if (!t) throw new Error(`Unknown team: ${code}`)
  return t
}

export const SEED_MATCHES: Match[] = [
  {
    id: "wc26-001",
    stage: "group",
    group: "A",
    matchday: 1,
    homeTeam: team("USA"),
    awayTeam: team("COL"),
    homeScore: 2,
    awayScore: 1,
    status: "live",
    minute: 67,
    kickoffUtc: "2026-06-11T19:00:00Z",
    venue: "MetLife Stadium",
    city: "East Rutherford, NJ",
    country: "USA",
    broadcastNote: "FOX / Telemundo · 3:00 PM ET",
    events: [
      { id: "e1", minute: 12, type: "goal", teamCode: "USA", playerName: "Christian Pulisic", detail: "Right foot" },
      { id: "e2", minute: 34, type: "goal", teamCode: "COL", playerName: "Luis Díaz", detail: "Header" },
      { id: "e3", minute: 58, type: "yellow_card", teamCode: "COL", playerName: "Wilmar Barrios" },
      { id: "e4", minute: 67, type: "goal", teamCode: "USA", playerName: "Folarin Balogun", detail: "Left foot" },
    ],
  },
  {
    id: "wc26-002",
    stage: "group",
    group: "A",
    matchday: 1,
    homeTeam: team("MEX"),
    awayTeam: team("CAN"),
    homeScore: 1,
    awayScore: 1,
    status: "halftime",
    minute: 45,
    kickoffUtc: "2026-06-11T22:00:00Z",
    venue: "Estadio Azteca",
    city: "Mexico City",
    country: "MEX",
    broadcastNote: "Univision · 5:00 PM CT",
    events: [
      { id: "e5", minute: 23, type: "goal", teamCode: "MEX", playerName: "Santiago Giménez" },
      { id: "e6", minute: 41, type: "goal", teamCode: "CAN", playerName: "Alphonso Davies" },
    ],
  },
  {
    id: "wc26-003",
    stage: "group",
    group: "B",
    matchday: 1,
    homeTeam: team("BRA"),
    awayTeam: team("MAR"),
    homeScore: 0,
    awayScore: 0,
    status: "live",
    minute: 52,
    kickoffUtc: "2026-06-12T01:00:00Z",
    venue: "SoFi Stadium",
    city: "Inglewood, CA",
    country: "USA",
    broadcastNote: "FOX · 6:00 PM PT",
    events: [
      { id: "e7", minute: 38, type: "yellow_card", teamCode: "BRA", playerName: "Casemiro" },
    ],
  },
  {
    id: "wc26-004",
    stage: "group",
    group: "C",
    matchday: 1,
    homeTeam: team("ARG"),
    awayTeam: team("SEN"),
    homeScore: 3,
    awayScore: 0,
    status: "finished",
    kickoffUtc: "2026-06-12T19:00:00Z",
    venue: "Mercedes-Benz Stadium",
    city: "Atlanta, GA",
    country: "USA",
    broadcastNote: "FS1 · 3:00 PM ET",
    events: [
      { id: "e8", minute: 8, type: "goal", teamCode: "ARG", playerName: "Lionel Messi", detail: "Penalty" },
      { id: "e9", minute: 31, type: "goal", teamCode: "ARG", playerName: "Lautaro Martínez" },
      { id: "e10", minute: 72, type: "goal", teamCode: "ARG", playerName: "Ángel Di María" },
    ],
  },
  {
    id: "wc26-005",
    stage: "group",
    group: "D",
    matchday: 1,
    homeTeam: team("FRA"),
    awayTeam: team("AUS"),
    homeScore: null,
    awayScore: null,
    status: "scheduled",
    kickoffUtc: "2026-06-13T19:00:00Z",
    venue: "Lumen Field",
    city: "Seattle, WA",
    country: "USA",
    broadcastNote: "FOX · 12:00 PM PT",
    events: [],
  },
  {
    id: "wc26-006",
    stage: "group",
    group: "E",
    matchday: 1,
    homeTeam: team("ENG"),
    awayTeam: team("JPN"),
    homeScore: null,
    awayScore: null,
    status: "scheduled",
    kickoffUtc: "2026-06-13T22:00:00Z",
    venue: "Gillette Stadium",
    city: "Foxborough, MA",
    country: "USA",
    broadcastNote: "FS1 · 6:00 PM ET",
    events: [],
  },
  {
    id: "wc26-007",
    stage: "group",
    group: "F",
    matchday: 1,
    homeTeam: team("ESP"),
    awayTeam: team("KOR"),
    homeScore: null,
    awayScore: null,
    status: "scheduled",
    kickoffUtc: "2026-06-14T19:00:00Z",
    venue: "AT&T Stadium",
    city: "Arlington, TX",
    country: "USA",
    broadcastNote: "FOX · 2:00 PM CT",
    events: [],
  },
  {
    id: "wc26-008",
    stage: "group",
    group: "G",
    matchday: 1,
    homeTeam: team("GER"),
    awayTeam: team("URU"),
    homeScore: null,
    awayScore: null,
    status: "scheduled",
    kickoffUtc: "2026-06-14T22:00:00Z",
    venue: "NRG Stadium",
    city: "Houston, TX",
    country: "USA",
    broadcastNote: "FS1 · 5:00 PM CT",
    events: [],
  },
]

export const SEED_STANDINGS: GroupStanding[] = [
  { group: "A", team: team("USA"), played: 1, won: 1, drawn: 0, lost: 0, goalsFor: 2, goalsAgainst: 1, goalDifference: 1, points: 3 },
  { group: "A", team: team("MEX"), played: 1, won: 0, drawn: 1, lost: 0, goalsFor: 1, goalsAgainst: 1, goalDifference: 0, points: 1 },
  { group: "A", team: team("CAN"), played: 1, won: 0, drawn: 1, lost: 0, goalsFor: 1, goalsAgainst: 1, goalDifference: 0, points: 1 },
  { group: "A", team: team("COL"), played: 1, won: 0, drawn: 0, lost: 1, goalsFor: 1, goalsAgainst: 2, goalDifference: -1, points: 0 },
  { group: "B", team: team("BRA"), played: 1, won: 0, drawn: 1, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 1 },
  { group: "B", team: team("MAR"), played: 1, won: 0, drawn: 1, lost: 0, goalsFor: 0, goalsAgainst: 0, goalDifference: 0, points: 1 },
  { group: "C", team: team("ARG"), played: 1, won: 1, drawn: 0, lost: 0, goalsFor: 3, goalsAgainst: 0, goalDifference: 3, points: 3 },
  { group: "C", team: team("SEN"), played: 1, won: 0, drawn: 0, lost: 1, goalsFor: 0, goalsAgainst: 3, goalDifference: -3, points: 0 },
]

export function buildTournamentSnapshot(matches: Match[]): TournamentSnapshot {
  return {
    tournament: {
      name: "FIFA World Cup",
      edition: "2026",
      teams: 48,
      matches: 104,
      hosts: ["United States", "Mexico", "Canada"],
      startDate: "2026-06-11",
      endDate: "2026-07-19",
    },
    matches,
    standings: SEED_STANDINGS,
    stories: STORIES,
    lastUpdated: new Date().toISOString(),
    dataSource: "mock",
  }
}

export function getMatchById(id: string, matches: Match[]): Match | undefined {
  return matches.find((m) => m.id === id)
}

export const FORMAT_GROUPS = [
  { letter: "A", teams: ["USA", "MEX", "CAN", "COL"] },
  { letter: "B", teams: ["BRA", "MAR", "AUS", "SEN"] },
  { letter: "C", teams: ["ARG", "ESP", "JPN", "URU"] },
  { letter: "D", teams: ["FRA", "ENG", "KOR", "GER"] },
  { letter: "E", teams: ["POR", "NED", "COL", "MAR"] },
  { letter: "F", teams: ["BRA", "ARG", "USA", "FRA"] },
  { letter: "G", teams: ["ENG", "ESP", "MEX", "JPN"] },
  { letter: "H", teams: ["GER", "POR", "CAN", "SEN"] },
  { letter: "I", teams: ["NED", "URU", "KOR", "AUS"] },
  { letter: "J", teams: ["USA", "BRA", "ENG", "GER"] },
  { letter: "K", teams: ["ARG", "MEX", "POR", "JPN"] },
  { letter: "L", teams: ["FRA", "CAN", "ESP", "MAR"] },
] as const
